package com.example.dogtraininglog.database.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.dogtraininglog.database.DogTrainingDatabase;


@Entity(tableName = DogTrainingDatabase.DOG)
public class Dog {
    @PrimaryKey(autoGenerate = true)
    private int id;

    private int userId;

    @NonNull
    private String name;
    private String breed;
    private String notes;
    private int age;
    private String owner;

    /*Getters and setters*/

    /*This is id the primary key autogenerated byt the database.*/
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    /*Username*/
    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    public String getBreed() {
        return breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }
}

