package com.example.dogtraininglog.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.dogtraininglog.database.DogTrainingDatabase;


import java.util.Objects;

/*Stores a single user. This class is used to create and read rows in the user database.*/
@Entity(tableName = DogTrainingDatabase.USER_TABLE)
public class User {

    /*The primary key is a autogenerate number generated by room wrapper*/
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String username;
    private String password;
    private boolean isAdmin;

    /*Constructor for users */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
        isAdmin = false;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && isAdmin == user.isAdmin && Objects.equals(username, user.username) && Objects.equals(password, user.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username, password, isAdmin);
    }

    /*Get and set datebase id which is the primary key and autogenerated by the database*/

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /*Get and set admin*/

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }


    /*Get and set username*/
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    /*Get and set password*/
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
